server:
  port: 8080

spring:
  profiles:
    default: local

  application:
    name: kakao-oauth2-jwt

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 로그인 시작할 때 사용자를 보내는 카카오 로그인 페이지 주소
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            logout-uri: https://kauth.kakao.com/oauth/logout

app:
  auth:
    jwt:
      issuer: kakao-oauth2-jwt
      access-ttl-seconds: 900   # 15분
      refresh-ttl-seconds: 1209600 # 14일 (14 * 24 * 60 * 60)
      cookie-name: ACCESS_TOKEN
      cookie-secure: false      # 로컬은 false, 운영(HTTPS)은 true
      cookie-same-site: Lax     # 로컬 테스트에 적당
    redirect-after-login: /test # 카카오 로그인 성공 후, 서버가 어디로 보내줄지
  kakao:
    logout-redirect-uri: "http://localhost:8080/test/logout-complete" # 카카로 로그아웃 후, 서버가 어디로 보내줄지
